version: '3.8'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 1234:8080
    networks:
      - netw
  vue_app:
    build:
      context: ./vue-project
      dockerfile: Dockerfile
    container_name: vue-app
    ports:
      - "8080:3000"
    networks:
      - netw
    volumes:
      - ./dist:/dist

  flask-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: flask-app
    ports: 
      - "8081:80"
    networks:
      - netw
    environment:
      - PASSWORD_PG=password
      - PORT_PG=5432
      - HOST_PG=postgres-db
      - USER_PG=postgres
  
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      USER_PG: postgres
      PASSWORD_PG: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
      - netw
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  netw:
    driver: bridge

volumes:
  postgres-data:

